#!/bin/bash
### BEGIN INIT INFO
# Provides:             onlined
# Required-Start:       networking
# Required-Stop:        
# Default-Start:        S
# Default-Stop:         0 6
# Description:          Daemon using ifupdown to actively maintain networking.
# Short-Description:    onlined
### END INIT INFO


function main() {
  action="${1}"
  onlined=/usr/local/bin/onlined
  rundir=/run/onlined
  pidfile="${rundir}"/onlined.pid

  case "${action}" in
    start)
      start
      ;;
    stop)
      stop
      ;;
    restart)
      stop && start
      ;;
    status)
      status
      ;;
    *)
      invalid
      ;;
  esac
}


function start() {
  mkdir -p "${rundir}" || fail "Could not create run directory:  '${rundir}'"
  test -e "${pidfile}" && fail "PID file already exists:  '${pidfile}'"
  nohup "${onlined}" > /var/log/onlined.log 2>&1 &
  echo "${!}" > "${pidfile}"
}


function stop() {
  pid="$(cat "${pidfile}")" || fail "Failed to check PID file:  '${pidfile}'"
  kill "${pid}"
  while ps -p "${pid}" > /dev/null; do
    sleep .5
  done
  rm "${pidfile}" || fail "Failed to remove PID file:  '${pidfile}'"
}


function status() {
  pid="$(cat "${pidfile}")" || fail "Failed to check PID file:  '${pidfile}'"
  ps -lfp "${pid}"
}


function invalid() {
  echo "Invalid service action:  '${action}'"
  return 1
}


function fail() {
  printf 'Error:  %s\n' "${1}"
  exit 1
}


main "${@}"
